In [ ]:
from google.colab import drive

In [ ]:
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import pandas as pd
import numpy as np
from sklearn import linear_model
from sklearn.model_selection import train_test_split

In [ ]:
data = pd.read_csv('/content/drive/MyDrive/Daylight autonomy predection /daylight autonomy data.csv')

In [ ]:
data.head()

width  Length  Height   WWR       A_D_A
0      3       6       3  0.55   86.361111
1      4       3       3  0.55  100.000000
2      5       3       3  0.55  100.000000
3      6       3       3  0.55  100.000000
4      7       3       3  0.55  100.000000

In [ ]:
data.describe()

width      Length      Height           WWR       A_D_A
count  128.000000  128.000000  128.000000  1.280000e+02  128.000000
mean     6.500000    6.523438    3.500000  5.500000e-01   90.470146
std      2.300291    2.279539    0.501965  1.114585e-16   13.417570
min      3.000000    3.000000    3.000000  5.500000e-01   48.675000
25%      4.750000    5.000000    3.000000  5.500000e-01   85.185268
50%      6.500000    6.500000    3.500000  5.500000e-01   98.362848
75%      8.250000    8.250000    4.000000  5.500000e-01  100.000000
max     10.000000   10.000000    4.000000  5.500000e-01  100.000000

In [ ]:
y= data["A_D_A"]

In [ ]:
input_data = data.drop(['A_D_A'] , axis=1)
input_data

width  Length  Height   WWR  floor_area  volume
0        3       6       3  0.55          18      54
1        4       3       3  0.55          12      36
2        5       3       3  0.55          15      45
3        6       3       3  0.55          18      54
4        7       3       3  0.55          21      63
..     ...     ...     ...   ...         ...     ...
123      6      10       4  0.55          60     240
124      7      10       4  0.55          70     280
125      8      10       4  0.55          80     320
126      9      10       4  0.55          90     360
127     10      10       4  0.55         100     400

[128 rows x 6 columns]

In [ ]:
input_data['floor_area']= input_data['width']*input_data['Length']
input_data['volume']= input_data['width']*input_data['Length']*input_data['Height']
input_data

width  Length  Height   WWR  floor_area  volume
0        3       6       3  0.55          18      54
1        4       3       3  0.55          12      36
2        5       3       3  0.55          15      45
3        6       3       3  0.55          18      54
4        7       3       3  0.55          21      63
..     ...     ...     ...   ...         ...     ...
123      6      10       4  0.55          60     240
124      7      10       4  0.55          70     280
125      8      10       4  0.55          80     320
126      9      10       4  0.55          90     360
127     10      10       4  0.55         100     400

[128 rows x 6 columns]

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(input_data, y, test_size=0.25, random_state = 42)
model = linear_model.LinearRegression()

In [ ]:
model.fit(X_train, y_train)

LinearRegression()

In [ ]:
y_pred = model.predict(X_test)
y_pred

array([ 82.42947786,  72.10523582,  94.27317929,  92.1512545 ,
        87.99429336,  57.88594055, 107.2260452 ,  75.80669477,
        96.57613056,  87.9893092 , 101.31412919,  88.82169826,
       108.20803055, 104.35036379,  82.28696193,  73.70512472,
        84.7553285 ,  95.24749624,  88.55222447, 100.56203352,
        93.99351243,  99.99771566,  95.59861025,  99.72466031,
        79.42287618,  81.79440314, 107.02964813, 105.12447515,
        85.67007007,  86.32453108,  99.45160496,  75.98090275])

In [ ]:
model.coef_


array([-2.48394416e+00, -8.76781424e+00, -1.33358487e+00,  9.76996262e-15,
       -7.66582761e-02,  2.09793493e-01])

In [ ]:
model.intercept_

140.43500397315253

In [ ]:
model.score(X_train, y_train)

0.8385574691687263

In [ ]:
model.score(X_test, y_test)

0.7898314605918616

In [ ]:
model.predict([[6,6,6,0.5,36,216]]) #predecting daylight autonomy of 6x6x6 room 

/usr/local/lib/python3.8/dist-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([107.47864088])